Haze4KConfig:
  haze_dir: ../../dataset/Haze4K/train/haze/
  gt_dir: ../../dataset/Haze4K/train/gt/
  dst: ../../dataset/TSIDdataset/
  img_size: 512
  batch_size: 8
  num_workers: 0

DynamicAttention2d:
  adaptive_avg_pool: 1
  fc1: 1
  fc2: 1
  K:


DynamicConvBlock:
  in_channels:
  out_channels:
  kernel_size:
  stride:
  padding:
  dilation: 1
  groups: 1
  bias: True
  K: 4
  batch_norm: False